services:
  mongodb:
    image: "mongo:latest"
    networks:
      - dynotxt
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: "redis:latest"
    networks:
      - dynotxt
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb:/data

  server:
    build: ./server
    ports:
      - 4000:80
    networks:
      - dynotxt
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./server:/home
    restart: always

  client:
    build: ./client
    ports:
      - 3000:5173
    networks:
      - dynotxt
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./client:/home
    restart: always
     
networks:
  dynotxt:
    name: dynotxt
