# Use the official Node.js image as base
FROM node:alpine

# Set working directory inside the container
WORKDIR /home

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install dependencies using yarn
RUN yarn install

# Copy the rest of the application code to the working directory
COPY . .

ENV PORT=80

EXPOSE 80

# Command to run the application
CMD ["yarn", "dev"]